DROP TABLE IF EXISTS userComments;

CREATE TABLE userComments (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    name TEXT NOT NULL,
    email TEXT NOT NULL,
    telefone TEXT NOT NULL,
    comentario TEXT,
);
